#spring :
#  datasource:
#    url: jdbc:mariadb://brep-rdb-01.cpu6sn7n18c0.ap-northeast-2.rds.amazonaws.com:3306/brep_rdb_01
#    driver-class-name : org.mariadb.jdbc.Driver
#    username: minholee93
#    password: markminholee93
